[observability]
# Other values include trace, debug, warn and error
log-level = "info"
observation-path = "/var/run/ntpd-rs/observe"

# Pool servers from ntppool.org. See http://www.pool.ntp.org/join.html
# for more information
#[[source]]
#mode = "ed"
#address = "ntp-ed.dyndns.weinigel.se"
#key = "4195704e51973badd982c4a0141b353001d8d56b9ef82c50ef8aca892d7afeca"

[[source]]
mode = "ed"
address = "localhost:123"
key = "b8425a8a0789b5b9acf5e31e88e18d1d13babbcec4367a0c0574784ef80043a9"

# Below are configured various thresholds beyond which ntpd-rs will not
# change the system clock. CHANGE THESE TO MATCH YOUR SECURITY NEEDS!
# For guidance, see OPERATIONAL_CONSIDERATIONS.md
[synchronization]
single-step-panic-threshold = 1800
startup-step-panic-threshold = { forward="inf", backward = 1800 }
#accumulated-step-panic-threshold = 1800
#minimum-agreeing-sources = 3
